FROM bigbluebutton/greenlight:v3-alpine

# https://hub.docker.com/layers/greenlight/bigbluebutton/greenlight/v3/images/sha256-24f96c2140a475586ab26bb855857050aefc4a176b29b805390a3fddcc111283?context=explore

ENV SECRET_KEY_BASE=X18e3V9oiTygI27XDSW47Ab372lLZQ4x
ENV RAILS_MAX_THREADS=100

RUN gem install sqlite3

ENTRYPOINT [ ]
# ENTRYPOINT ["./bin/start"]

